name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        mongodb-version: [7.0]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Clean npm cache
      run: |
        echo "Cleaning npm cache..."
        npm cache clean --force
        
    - name: Setup backend environment
      run: |
        echo "Node version:"
        node --version
        echo "NPM version:"
        npm --version
        
    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        echo "Installing backend dependencies..."
        npm install --verbose
        
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        
    - name: Run Linter
      working-directory: ./backend
      run: npm run lint
      
    - name: Run Tests
      working-directory: ./backend
      run: npm test
      env:
        CI: true
        NODE_ENV: test
        MONGODB_URI: mongodb://localhost:27017/quantummftools_test
        
    - name: Build
      working-directory: ./backend
      run: npm run build --if-present