name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        mongodb-version: [7.0]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install Dependencies
      run: |
        cd backend
        npm ci
        
    - name: Run Linter
      run: |
        cd backend
        npm run lint
      
    - name: Run Tests
      run: |
        cd backend
        npm test
      env:
        CI: true
        MONGODB_URI: mongodb://localhost:27017/quantummftools_test
        
    - name: Build
      run: |
        cd backend
        npm run build --if-present